"""Möbius Resonance Factoring (MRF).

A novel factoring algorithm based on the "Möbius Resonance" phenomenon:
the orbit of the rational parameter t₀ = b/(a+c) = 1/2 (for the root
PPT (3,4,5)) under the semigroup generated by the three Berggren Möbius
transforms acting on Q/NZ has a birthday-paradox collision structure that
reveals factors of N via CRT divergence.

THEORY
------
For a Pythagorean triple (a,b,c) with a²+b²=c², define the rational
parameter t = b/(a+c) ∈ (0,1).  The Berggren tree generates all PPTs via
three Möbius transforms on t:

  U(t) = t/(1+t)        (contracting toward 0)
  A(t) = (t+1)/(t+2)    (contracting toward the golden-ratio conjugate)
  D(t) = 1/(2+t)        (contracting toward √2 - 1)

Starting from t₀ = 1/2 (the root triple (3,4,5)), repeated application
generates all PPTs.

Each Möbius transform acts on the pair (num, den) representing t = num/den:

  U: (num, den) ↦ (num, num + den)
  A: (num, den) ↦ (num + den, num + 2·den)
  D: (num, den) ↦ (den, num + 2·den)

In matrix form (acting on column vector [num; den]):

  M_U = [[1, 0], [1, 1]]
  M_A = [[1, 1], [1, 2]]
  M_D = [[0, 1], [1, 2]]

All three matrices lie in SL₂(Z) (det = 1).

RESONANCE PHENOMENON
-------------------
For a semiprime N = pq, consider the orbit of t₀ = 1/2 under the semigroup
generated by {U, A, D} acting on Q/NZ.

By CRT, the orbit mod N decomposes into the product of the orbit mod p
and the orbit mod q.  The orbit sizes differ mod p and mod q, so the
dynamics "resonate" at different frequencies.

When a Möbius word W₁ produces a value W₁(t₀) that collides mod p with
another word W₂(t₀) but NOT mod q, the "resonance collision" reveals a
factor: the integer matrices M₁ and M₂ satisfy M₁·(1,2) ≡ M₂·(1,2) (mod p)
but not (mod q), so the entries of (M₁ - M₂) have gcd p with N.

PRACTICAL ALGORITHM
-------------------
1. Represent t = num/den as a pair (num, den) mod N.
2. Apply random Möbius words (sequences of U/A/D) to t₀ = (1, 2).
3. Track the orbit using distinguished-point hashing: only store points
   where both num and den have `distinguished_bits` low bits zero.
4. When a collision is detected (same (num, den) via different words):
   - The two words W₁, W₂ give the same rational t mod N.
   - Compute the integer matrices M₁, M₂ for each word.
   - The entries of (M₁ - M₂) give candidates for gcd with N.
   - Also try trace differences, cross terms, and the action on (1, 2).
5. If no collision yields a factor, restart with fresh random words.

The distinguished-point method gives O(√p) storage for birthday-scale
collision detection, analogous to Pollard's rho with distinguished points.
"""
from __future__ import annotations

import random
from math import gcd
from typing import Optional

# ---------------------------------------------------------------------------
# Berggren Möbius matrices acting on (num, den) column vector
# ---------------------------------------------------------------------------
# U(t) = t/(1+t) = (1·num + 0·den) / (1·num + 1·den)  →  M_U = [[1,0],[1,1]]
# A(t) = (t+1)/(t+2) = (1·num + 1·den) / (1·num + 2·den)  →  M_A = [[1,1],[1,2]]
# D(t) = 1/(t+2) = (0·num + 1·den) / (1·num + 2·den)  →  M_D = [[0,1],[1,2]]

MAT_U: tuple[tuple[int, int], tuple[int, int]] = ((1, 0), (1, 1))
MAT_A: tuple[tuple[int, int], tuple[int, int]] = ((1, 1), (1, 2))
MAT_D: tuple[tuple[int, int], tuple[int, int]] = ((0, 1), (1, 2))

_MATRICES: dict[str, tuple[tuple[int, int], tuple[int, int]]] = {
    'U': MAT_U,
    'A': MAT_A,
    'D': MAT_D,
}

_STEP_LIST: list[str] = ['U', 'A', 'D']


# ---------------------------------------------------------------------------
# Core operations
# ---------------------------------------------------------------------------

def apply_mobius_word(
    t: tuple[int, int],
    word: str,
    N: int,
) -> tuple[int, int]:
    """Apply a sequence of U/A/D Möbius transforms to rational t = (num, den) mod N.

    Each step updates (num, den) according to the Berggren Möbius action:

      U: (num, den) ↦ (num, num + den)
      A: (num, den) ↦ (num + den, num + 2·den)
      D: (num, den) ↦ (den, num + 2·den)

    All arithmetic is performed mod N.

    Args:
        t: The starting rational as (num, den).
        word: A string of 'U', 'A', 'D' characters (e.g., "UADUD").
        N: The modulus (semiprime to factor).

    Returns:
        The resulting (num, den) pair mod N.
    """
    num, den = t
    for ch in word:
        if ch == 'U':
            num, den = num % N, (num + den) % N
        elif ch == 'A':
            num, den = (num + den) % N, (num + 2 * den) % N
        elif ch == 'D':
            num, den = den % N, (num + 2 * den) % N
        else:
            raise ValueError(f"Unknown Möbius step: {ch!r}")
    return (num, den)


def mobius_matrix(word: str) -> tuple[tuple[int, int], tuple[int, int]]:
    """Compute the 2×2 integer matrix for a Möbius word.

    The matrix is the product M_{sₖ} · ... · M_{s₂} · M_{s₁} where each
    M_{sᵢ} is the Berggren matrix for step sᵢ.  The product is taken in
    reverse of the order the word is read (since the leftmost transform
    acts first on the root vector).

    The resulting matrix M satisfies M · [1; 2] = [num; den] where
    (num, den) is the rational reached by applying the word to (1, 2).

    Args:
        word: A string of 'U', 'A', 'D' characters.

    Returns:
        The 2×2 matrix as nested tuples ((a, b), (c, d)).
    """
    # Identity matrix
    a, b, c, d = 1, 0, 0, 1
    for ch in word:
        m = _MATRICES[ch]
        # Matrix multiply: new = M_ch · [[a,b],[c,d]]
        # This pre-multiplies so that the leftmost character in `word`
        # acts first on the root vector.
        # [[m00,m01],[m10,m11]] · [[a,b],[c,d]]
        na = m[0][0] * a + m[0][1] * c
        nb = m[0][0] * b + m[0][1] * d
        nc = m[1][0] * a + m[1][1] * c
        nd = m[1][0] * b + m[1][1] * d
        a, b, c, d = na, nb, nc, nd
    return ((a, b), (c, d))


def mat_vec_mul(
    M: tuple[tuple[int, int], tuple[int, int]],
    v: tuple[int, int],
    N: int,
) -> tuple[int, int]:
    """Multiply a 2×2 matrix by a 2-vector mod N."""
    return (
        (M[0][0] * v[0] + M[0][1] * v[1]) % N,
        (M[1][0] * v[0] + M[1][1] * v[1]) % N,
    )


# ---------------------------------------------------------------------------
# Factor extraction from collisions
# ---------------------------------------------------------------------------

def factor_from_collision(
    M1: tuple[tuple[int, int], tuple[int, int]],
    M2: tuple[tuple[int, int], tuple[int, int]],
    N: int,
) -> int | None:
    """Extract a non-trivial factor of N from two colliding Möbius matrices.

    When two different words W₁, W₂ produce the same (num, den) mod N,
    the corresponding integer matrices M₁, M₂ satisfy:

        M₁ · (1, 2) ≡ M₂ · (1, 2)   (mod N)

    so (M₁ - M₂) · (1, 2) ≡ 0 (mod N).  The entries of the difference
    matrix (and various derived quantities) may share a non-trivial gcd
    with N, revealing a factor.

    We try several candidate constructions:

    1. Raw entries of (M₁ - M₂).
    2. The action (M₁ - M₂) · (1, 2).
    3. The trace difference tr(M₁) - tr(M₂).
    4. Cross-term combinations.
    5. Determinant-like combinations of the difference matrix entries.

    Args:
        M1: The integer matrix for word W₁.
        M2: The integer matrix for word W₂.
        N: The semiprime to factor.

    Returns:
        A non-trivial factor of N, or None if none found.
    """
    a1, b1 = M1[0]
    c1, d1 = M1[1]
    a2, b2 = M2[0]
    c2, d2 = M2[1]

    da = a1 - a2
    db = b1 - b2
    dc = c1 - c2
    dd = d1 - d2

    # 1. Raw entries of the difference matrix
    for val in (da, db, dc, dd):
        g = gcd(abs(val), N)
        if 1 < g < N:
            return g

    # 2. Action of difference on the root vector (1, 2)
    v0 = da + 2 * db
    v1 = dc + 2 * dd
    for val in (v0, v1):
        g = gcd(abs(val), N)
        if 1 < g < N:
            return g

    # 3. Trace difference
    tr_diff = (a1 + d1) - (a2 + d2)
    g = gcd(abs(tr_diff), N)
    if 1 < g < N:
        return g

    # 4. Cross-term combinations
    for val in (da + dd, db + dc, da - dd, db - dc):
        g = gcd(abs(val), N)
        if 1 < g < N:
            return g

    # 5. Determinant of the difference matrix
    det_diff = da * dd - db * dc
    g = gcd(abs(det_diff), N)
    if 1 < g < N:
        return g

    # 6. Frobenius norm squared of the difference matrix
    frob = da * da + db * db + dc * dc + dd * dd
    g = gcd(frob, N)
    if 1 < g < N:
        return g

    return None


# ---------------------------------------------------------------------------
# Distinguished-point collision detection
# ---------------------------------------------------------------------------

def _generate_random_word(length: int, rng: random.Random) -> str:
    """Generate a random Möbius word of the given length."""
    return ''.join(rng.choice(_STEP_LIST) for _ in range(length))


def _is_distinguished(
    point: tuple[int, int],
    mask: int,
) -> bool:
    """Check if a (num, den) pair is "distinguished" (low bits are zero).

    A point is distinguished if both num and den have their low
    `distinguished_bits` bits equal to zero.  This occurs with probability
    2^(-2·distinguished_bits), giving O(√p) storage for birthday-scale
    collision detection.
    """
    num, den = point
    return (num & mask) == 0 and (den & mask) == 0


def detect_resonance(
    N: int,
    walk_steps: int = 30,
    num_walks: int = 50000,
    distinguished_bits: int = 8,
    seed: int | None = None,
) -> tuple[int, int] | None:
    """Detect resonance collisions in the Möbius orbit of t₀ = (1, 2) mod N.

    Generates random Möbius words and computes their action on the root
    rational t₀ = 1/2.  Distinguished points (where both num and den have
    low bits zero) are stored in a hash table.  When two different words
    produce the same distinguished point, we have a "resonance collision"
    and attempt to extract a factor.

    Args:
        N: The semiprime to factor.
        walk_steps: Length of each random Möbius word.
        num_walks: Maximum number of random words to try.
        distinguished_bits: Number of low bits that must be zero for a
            point to be distinguished.  Higher values mean fewer stored
            points but more work per point.
        seed: Random seed for reproducibility.

    Returns:
        A tuple (p, q) with p < q and p * q = N, or None if no factor found.
    """
    if N < 4:
        return None
    if N % 2 == 0:
        return (2, N // 2) if N > 2 else None

    rng = random.Random(seed)
    mask = (1 << distinguished_bits) - 1

    # Hash table mapping distinguished (num, den) → (word, integer matrix)
    seen: dict[tuple[int, int], str] = {}
    # We also store the integer matrices separately to avoid recomputation
    matrices: dict[tuple[int, int], tuple[tuple[int, int], tuple[int, int]]] = {}

    t0: tuple[int, int] = (1, 2)

    for _ in range(num_walks):
        word = _generate_random_word(walk_steps, rng)
        point = apply_mobius_word(t0, word, N)
        num, den = point

        # Direct gcd check on the denominator — if den shares a factor
        # with N, we've found a factor immediately.
        g = gcd(den, N)
        if 1 < g < N:
            return (min(g, N // g), max(g, N // g))

        # Also check the numerator
        g = gcd(num, N)
        if 1 < g < N:
            return (min(g, N // g), max(g, N // g))

        if not _is_distinguished(point, mask):
            continue

        if point in seen:
            other_word = seen[point]
            if other_word != word:
                M1 = mobius_matrix(word)
                M2 = matrices[point]
                # Verify the matrices agree mod N on the root vector
                v1 = mat_vec_mul(M1, t0, N)
                v2 = mat_vec_mul(M2, t0, N)
                if v1 == v2:
                    factor = factor_from_collision(M1, M2, N)
                    if factor is not None:
                        other = N // factor
                        return (min(factor, other), max(factor, other))
        else:
            seen[point] = word
            matrices[point] = mobius_matrix(word)

    return None


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def mobius_resonance_factor(
    N: int,
    max_steps: int = 100000,
    distinguished_bits: int = 8,
) -> tuple[int, int] | None:
    """Factor N using Möbius Resonance.

    Exploits the "Möbius Resonance" phenomenon: the orbit of t₀ = 1/2 under
    the Berggren Möbius semigroup {U, A, D} acting on Q/NZ has a birthday-
    paradox collision structure.  When the orbit mod p cycles back to a
    previously seen value but the orbit mod q does not, the collision
    between two Möbius words reveals a factor via the difference of their
    integer matrices.

    The algorithm uses distinguished-point hashing: only points where both
    num and den have `distinguished_bits` low bits zero are stored.  This
    gives O(√p) storage for birthday-scale collision detection.

    Args:
        N: The semiprime to factor.  Must be odd and > 1.
        max_steps: Maximum total number of random Möbius words to try.
            The search is divided across several walk-length configurations.
        distinguished_bits: Number of low bits that must be zero for a
            point to be distinguished.  Higher values reduce memory usage
            but require more work per distinguished point found.

    Returns:
        A tuple (p, q) with p <= q and p * q = N, or None if no
        non-trivial factor is found.
    """
    if N < 4:
        return None
    if N % 2 == 0:
        if N == 2:
            return None
        return (2, N // 2)

    # Perfect square fast path
    from math import isqrt
    s = isqrt(N)
    if s * s == N and s > 1:
        return (s, s)

    # Quick trial division for small factors
    for p in range(3, min(s + 1, 1000), 2):
        if N % p == 0:
            return (p, N // p)

    # Try several walk-length configurations.  Shorter words give smaller
    # matrices (faster arithmetic) but a smaller orbit; longer words give
    # a larger orbit but bigger matrices.  We sweep both directions.
    configs = [
        (20, max_steps // 4),
        (30, max_steps // 4),
        (40, max_steps // 4),
        (50, max_steps // 4),
    ]

    for walk_steps, num_walks in configs:
        if num_walks <= 0:
            continue
        result = detect_resonance(
            N,
            walk_steps=walk_steps,
            num_walks=num_walks,
            distinguished_bits=distinguished_bits,
        )
        if result is not None:
            p, q = result
            if p * q == N and 1 < p <= q < N:
                return (p, q)

    return None
